from PIL import Image
old_image = Image.open("monro.jpg")
red, green, blue = old_image.split()
coordinates_red_left = (100, 0 , red.width, red.height)
cropped_photo_red_left = red.crop(coordinates_red_left)
coordinates_red_right = (50, 0 , 646, red.height)
cropped_photo_red_right = red.crop(coordinates_red_right)
summ_red = Image.blend(cropped_photo_red_left, cropped_photo_red_right, 0.5).convert("L") 
coordinates_blue_right = (0, 0 , 596, blue.height)
cropped_photo_blue_right = blue.crop(coordinates_blue_right)
coordinates_blue_left = (50, 0 , 646, blue.height)
cropped_photo_blue_left = blue.crop(coordinates_blue_left)
summ_blue = Image.blend(cropped_photo_blue_right, cropped_photo_blue_left, 0.5).convert("L")
coordinates_gren = (50, 0 , 646, green.height)
cropped_photo_green = green.crop(coordinates_gren).convert("L")
merged_img = Image.merge("RGB", (summ_red, cropped_photo_green, summ_blue))
merged_img.thumbnail((80, 80))  
merged_img.save("new_monro.jpg")